name: fcpd_mapping_dashboard
channels:
  - conda-forge
dependencies:
  - pip
  - folium
  - geopandas
  - numpy
  - pandas
  - shapely
  - streamlit
  - pip:
    - openpolicedata
    - streamlit_folium